on:
  schedule:
    - cron: '53 20 * * 1,2,3,4,5'
  workflow_dispatch:

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI trigger on schedule
        id: step1
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN || secrets.CCI_TOKEN_FOR_PUBLIC_REPOS }}
